config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :vendedors
  #root to: "windows#entrada"
  root to: "clientes#index"
  #get'inicio' => 'vendedors/sign_in'
  #/vendedors/sign_in
  resources :lista_helados
  resources :lista_sabors
  resources :helados
  resources :sabors
  resources :salsas
  resources :chips
  resources :galleta
  resources :banos
  resources :copos
  resources :tipos
  resources :boleta
  resources :pedidos
  resources :venderors
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bano.rb
class Bano < ApplicationRecord
  has_many :helados
end

app/models/boletum.rb
class Boletum < ApplicationRecord
  belongs_to :Pedido
end

app/models/chip.rb
class Chip < ApplicationRecord
  has_many :helados
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :pedidos
end

app/models/copo.rb
class Copo < ApplicationRecord
  has_many :helados
end

app/models/galletum.rb
class Galletum < ApplicationRecord
  has_many :helados
end

app/models/helado.rb
class Helado < ApplicationRecord
  has_many :lista_helados
  has_many :lista_sabors
  
  belongs_to :Bano
  belongs_to :Chip
  belongs_to :Copo
  belongs_to :Galletum
  belongs_to :Salsa
  belongs_to :Tipo

end

app/models/lista_helado.rb
class ListaHelado < ApplicationRecord
  belongs_to :pedido
  belongs_to :helado
end

app/models/lista_sabor.rb
class ListaSabor < ApplicationRecord
  belongs_to :Sabor
  belongs_to :Helado
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :cliente
  belongs_to :venderor

  has_many :lista_helados
  has_many :boleta
end

app/models/sabor.rb
class Sabor < ApplicationRecord
  has_many  :lista_sabors
end

app/models/salsa.rb
class Salsa < ApplicationRecord
  has_many :helados
end

app/models/tipo.rb
class Tipo < ApplicationRecord
  has_many :helados
end

app/models/vendedor.rb
class Vendedor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venderor.rb
class Venderor < ApplicationRecord
  validates :nombre,presence:true
  validates :apellido_p,presence:true
  validates :apellido_m,presence:true
  validates :rut,presence:true
  validates :verifi,presence:true
  has_many :pedidos
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente Creado exitosamente!.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Datos del cliente actualizados.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente Eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :apellido_p, :apellido_m, :rut, :verifi)
    end
end

app/helpers/banos_helper.rb
module BanosHelper
end

app/helpers/boleta_helper.rb
module BoletaHelper
end

app/helpers/chips_helper.rb
module ChipsHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/copos_helper.rb
module CoposHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/clientes/_form.html.erb
<%= form_for(cliente) do |f| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :'Apellido paterno' %>
    <%= f.text_field :apellido_p %>
  </div>

  <div class="field">
    <%= f.label :'Apellido materno' %>
    <%= f.text_field :apellido_m %>
  </div>

  <div class="field">
    <%= f.label :Rut %>
    <%= f.number_field :rut %>
  </div>

  <div class="field">
    <%= f.label :'Codigo verificador' %>
    <%= f.text_field :verifi %>
  </div>

  <div class="actions">
    <%= f.submit :'Crear al cliente' %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Vista', @cliente %> |
<%= link_to 'Volver', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre:</th>
      <th>Apellido Paterno</th>
      <th>Apellido Materno</th>
      <th>Rut:</th>
      <th>Codigo verificador:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellido_p %></td>
        <td><%= cliente.apellido_m %></td>
        <td><%= cliente.rut %></td>
        <td><%= cliente.verifi %></td>
        <td><%= link_to 'Ver', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Estas seguro que deseas eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Volver', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Datos cliente: <h1>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Apellido Paterno:</strong>
  <%= @cliente.apellido_p %>
</p>

<p>
  <strong>Apellido Materno:</strong>
  <%= @cliente.apellido_m %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @cliente.rut %>
</p>

<p>
  <strong>Digito verificador:</strong>
  <%= @cliente.verifi %>
</p>

<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Volver', clientes_path %>