config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :vendedors
  #root to: "windows#entrada"
  root to: "clientes#index"
  #get'inicio' => 'vendedors/sign_in'
  #/vendedors/sign_in
  resources :lista_helados
  resources :lista_sabors
  resources :helados
  resources :sabors
  resources :salsas
  resources :chips
  resources :galleta
  resources :banos
  resources :copos
  resources :tipos
  resources :boleta
  resources :pedidos
  resources :venderors
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bano.rb
class Bano < ApplicationRecord
  has_many :helados
end

app/models/boletum.rb
class Boletum < ApplicationRecord
  belongs_to :Pedido
end

app/models/chip.rb
class Chip < ApplicationRecord
  has_many :helados
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :pedidos
end

app/models/copo.rb
class Copo < ApplicationRecord
  has_many :helados
end

app/models/galletum.rb
class Galletum < ApplicationRecord
  has_many :helados
end

app/models/helado.rb
class Helado < ApplicationRecord
  has_many :lista_helados
  has_many :lista_sabors
  
  belongs_to :Bano
  belongs_to :Chip
  belongs_to :Copo
  belongs_to :Galletum
  belongs_to :Salsa
  belongs_to :Tipo

end

app/models/lista_helado.rb
class ListaHelado < ApplicationRecord
  belongs_to :pedido
  belongs_to :helado
end

app/models/lista_sabor.rb
class ListaSabor < ApplicationRecord
  belongs_to :Sabor
  belongs_to :Helado
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :cliente
  belongs_to :venderor

  has_many :lista_helados
  has_many :boleta
end

app/models/sabor.rb
class Sabor < ApplicationRecord
  has_many  :lista_sabors
end

app/models/salsa.rb
class Salsa < ApplicationRecord
  has_many :helados
end

app/models/tipo.rb
class Tipo < ApplicationRecord
  has_many :helados
end

app/models/vendedor.rb
class Vendedor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venderor.rb
class Venderor < ApplicationRecord
  validates :nombre,presence:true
  validates :apellido_p,presence:true
  validates :apellido_m,presence:true
  validates :rut,presence:true
  validates :verifi,presence:true
  has_many :pedidos
end

app/controllers/venderors_controller.rb
class VenderorsController < ApplicationController
  before_action :set_venderor, only: [:login, :show, :edit, :update, :destroy]

  # GET /venderors
  # GET /venderors.json
  def login
  end

  def index
    @venderors = Venderor.all
  end

  # GET /venderors/1
  # GET /venderors/1.json
  def show
  end

  # GET /venderors/new
  def new
    @venderor = Venderor.new
  end

  # GET /venderors/1/edit
  def edit
  end

  # POST /venderors
  # POST /venderors.json
  def create
    @venderor = Venderor.new(venderor_params)

    respond_to do |format|
      if @venderor.save
        format.html { redirect_to @venderor, notice: 'Vendedor Creado!.' }
        format.json { render :show, status: :created, location: @venderor }
      else
        format.html { render :new }
        format.json { render json: @venderor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venderors/1
  # PATCH/PUT /venderors/1.json
  def update
    respond_to do |format|
      if @venderor.update(venderor_params)
        format.html { redirect_to @venderor, notice: 'Datos del Vendedor actualizados.' }
        format.json { render :show, status: :ok, location: @venderor }
      else
        format.html { render :edit }
        format.json { render json: @venderor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venderors/1
  # DELETE /venderors/1.json
  def destroy
    @venderor.destroy
    respond_to do |format|
      format.html { redirect_to venderors_url, notice: 'Vendedor Eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venderor
      @venderor = Venderor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venderor_params
      params.require(:venderor).permit(:nombre, :apellido_p, :apellido_m, :rut, :verifi, :clave)
    end
end

app/helpers/banos_helper.rb
module BanosHelper
end

app/helpers/boleta_helper.rb
module BoletaHelper
end

app/helpers/chips_helper.rb
module ChipsHelper
end

app/helpers/copos_helper.rb
module CoposHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/venderors_helper.rb
module VenderorsHelper
end

app/views/venderors/_form.html.erb
<%= form_for(venderor) do |f| %>
  <% if venderor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venderor.errors.count, "error") %> prohibited this venderor from being saved:</h2>

      <ul>
      <% venderor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %>
    <%= f.text_field :nombre,:placeholder => "Nombre del vendedor" %>
  </div>

  <div class="field">
    <%= f.label :'Apellido Paterno' %>
    <%= f.text_field :apellido_p ,:placeholder => "Apellido paterno"%>
  </div>

  <div class="field">
    <%= f.label :'Apellido Materno' %>
    <%= f.text_field :apellido_m ,:placeholder => "Apellido materno" %>
  </div>

  <div class="field">
    <%= f.label :Rut ,"Rut. sin puntos ni espacios"%>
    <%= f.number_field :rut ,:placeholder => "Ej:19033000"%>
  </div>

  <div class="field">
    <%= f.label :'Codigo verificador' %>
    <%= f.text_field :verifi,:placeholder => "Ej k" %>
  </div>

  <div class="field">
    <%= f.label :'Clave', "clave" %>
    <%= f.text_field :clave %>
  </div>

  <div class="actions">
    <%= f.submit "Crear al cliente", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/venderors/edit.html.erb
<h1>Editar Venderor</h1>

<%= render 'form', venderor: @venderor %>

<%= link_to 'Ver', @venderor %> |
<%= link_to 'Volver', venderors_path %>

app/views/venderors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Venderores:</h1>

<table>
  <thead>
    <tr>
      <th>Nombre:</th>
      <th>Apellido Paterno:</th>
      <th>Apellido materno:</th>
      <th>Rut:</th>
      <th>Cog verificador</th>
      <th>Clave</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venderors.each do |venderor| %>
      <tr>
        <td><%= venderor.nombre %></td>
        <td><%= venderor.apellido_p %></td>
        <td><%= venderor.apellido_m %></td>
        <td><%= venderor.rut %></td>
        <td><%= venderor.verifi %></td>
        <td><%= venderor.clave %></td>
        <td><%= link_to 'Ver', venderor %></td>
        <td><%= link_to 'Editar', edit_venderor_path(venderor) %></td>
        <td><%= link_to 'Eliminar', venderor, method: :delete, data: { confirm: 'Esta seguro que desea eliminar al cliente??' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo venderor', new_venderor_path %>
<hr>
<%= link_to 'LInk',clientes_path %>

app/views/venderors/login.html.erb
<h1> Bienvenido! </h1>
  <p1>Hola ....</p1>
  <p2> </p2>
  <%= link_to 'Volver', venderors_path %>

app/views/venderors/new.html.erb
<h1>Nuevo Venderor</h1>

<%= render 'form', venderor: @venderor %>

<%= link_to 'Volver', venderors_path %>

app/views/venderors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @venderor.nombre %>
</p>

<p>
  <strong>Apellido Paterno:</strong>
  <%= @venderor.apellido_p %>
</p>

<p>
  <strong>Apellido Materno:</strong>
  <%= @venderor.apellido_m %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @venderor.rut %>
</p>

<p>
  <strong>Codigo verificador:</strong>
  <%= @venderor.verifi %>
</p>
<p>
  <strong>Clave:</strong>
  <%= @venderor.clave %>
</p>

<%= link_to 'Editar', edit_venderor_path(@venderor) %> |
<%= link_to 'Volver', venderors_path %>