config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :vendedors
  #root to: "windows#entrada"
  root to: "clientes#index"
  #get'inicio' => 'vendedors/sign_in'
  #/vendedors/sign_in
  resources :lista_helados
  resources :lista_sabors
  resources :helados
  resources :sabors
  resources :salsas
  resources :chips
  resources :galleta
  resources :banos
  resources :copos
  resources :tipos
  resources :boleta
  resources :pedidos
  resources :venderors
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bano.rb
class Bano < ApplicationRecord
  has_many :helados
end

app/models/boletum.rb
class Boletum < ApplicationRecord
  belongs_to :Pedido
end

app/models/chip.rb
class Chip < ApplicationRecord
  has_many :helados
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :pedidos
end

app/models/copo.rb
class Copo < ApplicationRecord
  has_many :helados
end

app/models/galletum.rb
class Galletum < ApplicationRecord
  has_many :helados
end

app/models/helado.rb
class Helado < ApplicationRecord
  has_many :lista_helados
  has_many :lista_sabors
  
  belongs_to :Bano
  belongs_to :Chip
  belongs_to :Copo
  belongs_to :Galletum
  belongs_to :Salsa
  belongs_to :Tipo

end

app/models/lista_helado.rb
class ListaHelado < ApplicationRecord
  belongs_to :pedido
  belongs_to :helado
end

app/models/lista_sabor.rb
class ListaSabor < ApplicationRecord
  belongs_to :Sabor
  belongs_to :Helado
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :cliente
  belongs_to :venderor

  has_many :lista_helados
  has_many :boleta
end

app/models/sabor.rb
class Sabor < ApplicationRecord
  has_many  :lista_sabors
end

app/models/salsa.rb
class Salsa < ApplicationRecord
  has_many :helados
end

app/models/tipo.rb
class Tipo < ApplicationRecord
  has_many :helados
end

app/models/vendedor.rb
class Vendedor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venderor.rb
class Venderor < ApplicationRecord
  validates :nombre,presence:true
  validates :apellido_p,presence:true
  validates :apellido_m,presence:true
  validates :rut,presence:true
  validates :verifi,presence:true
  has_many :pedidos
end

app/controllers/banos_controller.rb
class BanosController < ApplicationController
  before_action :set_bano, only: [:show, :edit, :update, :destroy]

  # GET /banos
  # GET /banos.json
  def index
    @banos = Bano.all
  end

  # GET /banos/1
  # GET /banos/1.json
  def show
  end

  # GET /banos/new
  def new
    @bano = Bano.new
  end

  # GET /banos/1/edit
  def edit
  end

  # POST /banos
  # POST /banos.json
  def create
    @bano = Bano.new(bano_params)

    respond_to do |format|
      if @bano.save
        format.html { redirect_to @bano, notice: 'Bano was successfully created.' }
        format.json { render :show, status: :created, location: @bano }
      else
        format.html { render :new }
        format.json { render json: @bano.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banos/1
  # PATCH/PUT /banos/1.json
  def update
    respond_to do |format|
      if @bano.update(bano_params)
        format.html { redirect_to @bano, notice: 'Bano was successfully updated.' }
        format.json { render :show, status: :ok, location: @bano }
      else
        format.html { render :edit }
        format.json { render json: @bano.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banos/1
  # DELETE /banos/1.json
  def destroy
    @bano.destroy
    respond_to do |format|
      format.html { redirect_to banos_url, notice: 'Bano was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bano
      @bano = Bano.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bano_params
      params.require(:bano).permit(:descripcion, :valor)
    end
end

app/helpers/banos_helper.rb
module BanosHelper
end

app/helpers/boleta_helper.rb
module BoletaHelper
end

app/helpers/chips_helper.rb
module ChipsHelper
end

app/helpers/copos_helper.rb
module CoposHelper
end

app/helpers/sabors_helper.rb
module SaborsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/banos/_form.html.erb
<%= form_for(bano) do |f| %>
  <% if bano.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bano.errors.count, "error") %> prohibited this bano from being saved:</h2>

      <ul>
      <% bano.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_field :descripcion %>
  </div>

  <div class="field">
    <%= f.label :valor %>
    <%= f.number_field :valor %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banos/edit.html.erb
<h1>Editing Bano</h1>

<%= render 'form', bano: @bano %>

<%= link_to 'Show', @bano %> |
<%= link_to 'Back', banos_path %>

app/views/banos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Banos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banos.each do |bano| %>
      <tr>
        <td><%= bano.descripcion %></td>
        <td><%= bano.valor %></td>
        <td><%= link_to 'Show', bano %></td>
        <td><%= link_to 'Edit', edit_bano_path(bano) %></td>
        <td><%= link_to 'Destroy', bano, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bano', new_bano_path %>

app/views/banos/new.html.erb
<h1>New Bano</h1>

<%= render 'form', bano: @bano %>

<%= link_to 'Back', banos_path %>

app/views/banos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @bano.descripcion %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @bano.valor %>
</p>

<%= link_to 'Edit', edit_bano_path(@bano) %> |
<%= link_to 'Back', banos_path %>