config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :vendedors
  #root to: "windows#entrada"
  root to: "clientes#index"
  #get'inicio' => 'vendedors/sign_in'
  #/vendedors/sign_in
  resources :lista_helados
  resources :lista_sabors
  resources :helados
  resources :sabors
  resources :salsas
  resources :chips
  resources :galleta
  resources :banos
  resources :copos
  resources :tipos
  resources :boleta
  resources :pedidos
  resources :venderors
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bano.rb
class Bano < ApplicationRecord
  has_many :helados
end

app/models/boletum.rb
class Boletum < ApplicationRecord
  belongs_to :Pedido
end

app/models/chip.rb
class Chip < ApplicationRecord
  has_many :helados
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :pedidos
end

app/models/copo.rb
class Copo < ApplicationRecord
  has_many :helados
end

app/models/galletum.rb
class Galletum < ApplicationRecord
  has_many :helados
end

app/models/helado.rb
class Helado < ApplicationRecord
  has_many :lista_helados
  has_many :lista_sabors
  
  belongs_to :Bano
  belongs_to :Chip
  belongs_to :Copo
  belongs_to :Galletum
  belongs_to :Salsa
  belongs_to :Tipo

end

app/models/lista_helado.rb
class ListaHelado < ApplicationRecord
  belongs_to :pedido
  belongs_to :helado
end

app/models/lista_sabor.rb
class ListaSabor < ApplicationRecord
  belongs_to :Sabor
  belongs_to :Helado
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :cliente
  belongs_to :venderor

  has_many :lista_helados
  has_many :boleta
end

app/models/sabor.rb
class Sabor < ApplicationRecord
  has_many  :lista_sabors
end

app/models/salsa.rb
class Salsa < ApplicationRecord
  has_many :helados
end

app/models/tipo.rb
class Tipo < ApplicationRecord
  has_many :helados
end

app/models/vendedor.rb
class Vendedor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venderor.rb
class Venderor < ApplicationRecord
  validates :nombre,presence:true
  validates :apellido_p,presence:true
  validates :apellido_m,presence:true
  validates :rut,presence:true
  validates :verifi,presence:true
  has_many :pedidos
end

app/controllers/lista_sabors_controller.rb
class ListaSaborsController < ApplicationController
  before_action :set_lista_sabor, only: [:show, :edit, :update, :destroy]

  # GET /lista_sabors
  # GET /lista_sabors.json
  def index
    @lista_sabors = ListaSabor.all
  end

  # GET /lista_sabors/1
  # GET /lista_sabors/1.json
  def show
  end

  # GET /lista_sabors/new
  def new
    @lista_sabor = ListaSabor.new
  end

  # GET /lista_sabors/1/edit
  def edit
  end

  # POST /lista_sabors
  # POST /lista_sabors.json
  def create
    @lista_sabor = ListaSabor.new(lista_sabor_params)

    respond_to do |format|
      if @lista_sabor.save
        format.html { redirect_to @lista_sabor, notice: 'Lista sabor was successfully created.' }
        format.json { render :show, status: :created, location: @lista_sabor }
      else
        format.html { render :new }
        format.json { render json: @lista_sabor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lista_sabors/1
  # PATCH/PUT /lista_sabors/1.json
  def update
    respond_to do |format|
      if @lista_sabor.update(lista_sabor_params)
        format.html { redirect_to @lista_sabor, notice: 'Lista sabor was successfully updated.' }
        format.json { render :show, status: :ok, location: @lista_sabor }
      else
        format.html { render :edit }
        format.json { render json: @lista_sabor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lista_sabors/1
  # DELETE /lista_sabors/1.json
  def destroy
    @lista_sabor.destroy
    respond_to do |format|
      format.html { redirect_to lista_sabors_url, notice: 'Lista sabor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lista_sabor
      @lista_sabor = ListaSabor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lista_sabor_params
      params.require(:lista_sabor).permit(:helado_id, :sabor)
    end
end

app/helpers/banos_helper.rb
module BanosHelper
end

app/helpers/boleta_helper.rb
module BoletaHelper
end

app/helpers/chips_helper.rb
module ChipsHelper
end

app/helpers/copos_helper.rb
module CoposHelper
end

app/helpers/lista_sabors_helper.rb
module ListaSaborsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/lista_sabors/_form.html.erb
<%= form_for(lista_sabor) do |f| %>
  <% if lista_sabor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lista_sabor.errors.count, "error") %> prohibited this lista_sabor from being saved:</h2>

      <ul>
      <% lista_sabor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :helado_id %>
    <%= f.number_field :helado_id %>
  </div>

  <div class="field">
    <%= f.label :sabor %>
    <%= f.number_field :sabor %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lista_sabors/edit.html.erb
<h1>Editing Lista Sabor</h1>

<%= render 'form', lista_sabor: @lista_sabor %>

<%= link_to 'Show', @lista_sabor %> |
<%= link_to 'Back', lista_sabors_path %>

app/views/lista_sabors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista Sabors</h1>

<table>
  <thead>
    <tr>
      <th>Helado</th>
      <th>Sabor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lista_sabors.each do |lista_sabor| %>
      <tr>
        <td><%= lista_sabor.helado_id %></td>
        <td><%= lista_sabor.sabor %></td>
        <td><%= link_to 'Show', lista_sabor %></td>
        <td><%= link_to 'Edit', edit_lista_sabor_path(lista_sabor) %></td>
        <td><%= link_to 'Destroy', lista_sabor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lista Sabor', new_lista_sabor_path %>

app/views/lista_sabors/new.html.erb
<h1>New Lista Sabor</h1>

<%= render 'form', lista_sabor: @lista_sabor %>

<%= link_to 'Back', lista_sabors_path %>

app/views/lista_sabors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Helado:</strong>
  <%= @lista_sabor.helado_id %>
</p>

<p>
  <strong>Sabor:</strong>
  <%= @lista_sabor.sabor %>
</p>

<%= link_to 'Edit', edit_lista_sabor_path(@lista_sabor) %> |
<%= link_to 'Back', lista_sabors_path %>